package com.fangdeng.server.dto;

import java.util.Date;

public class GoodsLabelDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.goods_label_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private Long goodsLabelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.label_name
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.label_visible
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private Byte labelVisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.label_sort
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private Integer labelSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.store_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.del_flag
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private Byte delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.create_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_label.update_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.goods_label_id
     *
     * @return the value of goods_label.goods_label_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public Long getGoodsLabelId() {
        return goodsLabelId;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.goods_label_id
     *
     * @return the value of goods_label.goods_label_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getGoodsLabelIdByFieldName() {
        return "goodsLabelId";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.goods_label_id
     *
     * @param goodsLabelId the value for goods_label.goods_label_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setGoodsLabelId(Long goodsLabelId) {
        this.goodsLabelId = goodsLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.label_name
     *
     * @return the value of goods_label.label_name
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getLabelName() {
        return labelName;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.label_name
     *
     * @return the value of goods_label.label_name
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getLabelNameByFieldName() {
        return "labelName";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.label_name
     *
     * @param labelName the value for goods_label.label_name
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.label_visible
     *
     * @return the value of goods_label.label_visible
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public Byte getLabelVisible() {
        return labelVisible;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.label_visible
     *
     * @return the value of goods_label.label_visible
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getLabelVisibleByFieldName() {
        return "labelVisible";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.label_visible
     *
     * @param labelVisible the value for goods_label.label_visible
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setLabelVisible(Byte labelVisible) {
        this.labelVisible = labelVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.label_sort
     *
     * @return the value of goods_label.label_sort
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public Integer getLabelSort() {
        return labelSort;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.label_sort
     *
     * @return the value of goods_label.label_sort
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getLabelSortByFieldName() {
        return "labelSort";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.label_sort
     *
     * @param labelSort the value for goods_label.label_sort
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setLabelSort(Integer labelSort) {
        this.labelSort = labelSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.store_id
     *
     * @return the value of goods_label.store_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public Long getStoreId() {
        return storeId;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.store_id
     *
     * @return the value of goods_label.store_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getStoreIdByFieldName() {
        return "storeId";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.store_id
     *
     * @param storeId the value for goods_label.store_id
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.del_flag
     *
     * @return the value of goods_label.del_flag
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public Byte getDelFlag() {
        return delFlag;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.del_flag
     *
     * @return the value of goods_label.del_flag
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getDelFlagByFieldName() {
        return "delFlag";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.del_flag
     *
     * @param delFlag the value for goods_label.del_flag
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.create_time
     *
     * @return the value of goods_label.create_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.create_time
     *
     * @return the value of goods_label.create_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getCreateTimeByFieldName() {
        return "createTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.create_time
     *
     * @param createTime the value for goods_label.create_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.update_time
     *
     * @return the value of goods_label.update_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_label.update_time
     *
     * @return the value of goods_label.update_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public String getUpdateTimeByFieldName() {
        return "updateTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_label.update_time
     *
     * @param updateTime the value for goods_label.update_time
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}