package com.fandeng.server.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GoodsSpecialPriceSync {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.id
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.goods_no
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private String goodsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.status
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.deleted
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.special_price
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private BigDecimal specialPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.create_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.update_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.start_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_special_price_sync.end_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.id
     *
     * @return the value of goods_special_price_sync.id
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public Long getId() {
        return id;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.id
     *
     * @return the value of goods_special_price_sync.id
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getIdByFieldName() {
        return "id";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.id
     *
     * @param id the value for goods_special_price_sync.id
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.goods_no
     *
     * @return the value of goods_special_price_sync.goods_no
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getGoodsNo() {
        return goodsNo;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.goods_no
     *
     * @return the value of goods_special_price_sync.goods_no
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getGoodsNoByFieldName() {
        return "goodsNo";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.goods_no
     *
     * @param goodsNo the value for goods_special_price_sync.goods_no
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.status
     *
     * @return the value of goods_special_price_sync.status
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public Byte getStatus() {
        return status;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.status
     *
     * @return the value of goods_special_price_sync.status
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getStatusByFieldName() {
        return "status";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.status
     *
     * @param status the value for goods_special_price_sync.status
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.deleted
     *
     * @return the value of goods_special_price_sync.deleted
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public Byte getDeleted() {
        return deleted;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.deleted
     *
     * @return the value of goods_special_price_sync.deleted
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getDeletedByFieldName() {
        return "deleted";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.deleted
     *
     * @param deleted the value for goods_special_price_sync.deleted
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.special_price
     *
     * @return the value of goods_special_price_sync.special_price
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public BigDecimal getSpecialPrice() {
        return specialPrice;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.special_price
     *
     * @return the value of goods_special_price_sync.special_price
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getSpecialPriceByFieldName() {
        return "specialPrice";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.special_price
     *
     * @param specialPrice the value for goods_special_price_sync.special_price
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setSpecialPrice(BigDecimal specialPrice) {
        this.specialPrice = specialPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.create_time
     *
     * @return the value of goods_special_price_sync.create_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.create_time
     *
     * @return the value of goods_special_price_sync.create_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getCreateTimeByFieldName() {
        return "createTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.create_time
     *
     * @param createTime the value for goods_special_price_sync.create_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.update_time
     *
     * @return the value of goods_special_price_sync.update_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.update_time
     *
     * @return the value of goods_special_price_sync.update_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getUpdateTimeByFieldName() {
        return "updateTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.update_time
     *
     * @param updateTime the value for goods_special_price_sync.update_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.start_time
     *
     * @return the value of goods_special_price_sync.start_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public Date getStartTime() {
        return startTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.start_time
     *
     * @return the value of goods_special_price_sync.start_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getStartTimeByFieldName() {
        return "startTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.start_time
     *
     * @param startTime the value for goods_special_price_sync.start_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.end_time
     *
     * @return the value of goods_special_price_sync.end_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public Date getEndTime() {
        return endTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_special_price_sync.end_time
     *
     * @return the value of goods_special_price_sync.end_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public String getEndTimeByFieldName() {
        return "endTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_special_price_sync.end_time
     *
     * @param endTime the value for goods_special_price_sync.end_time
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}