@startuml
start
if(供应商关店过期)then(yes)
    if(供应商状态)
    :boss触发关店;

    else
    :定时任务触发过期;
    endif

partition 共用逻辑 {
:供应商商品不做改动;
:商家关联商品数据库更新不可售状态;
:同步刷新Es索引库 sku spu;
:Es查询过滤;
:前端不可见关联sku;
    partition spu不可售逻辑 {
    :当 spu下无可售sku时,同步修改spu 不可售状态;
    :同步spu索引;
    :前端不可见关联spu;
    }
}
    if(供应商状态)
    :boss触发再次开店;

    else
    :boss更新供应商签约时间;
    endif

partition 共用可售逻辑 {
:过滤供应商商品可售商品;
    partition 可售商品 {
    :spu 已审核（非禁售）&未删除&上架;
    }
:根据供应商可售商品spu查询 关联商家导入商品;
:刷新商家商品ES索引库;
}
else if(供应商下架删除) then(yes)
:供应商下架删除;
if(供应商商品状态)
    :下架;
    if(操作spu) then(yes)
    :spu下架;
    :关联所有sku下架;
    :同步商家关联此商品spu为不可售;
    :同步商家关联此商品<所有>sku为不可售;
    else
    :sku下架;
    :当前sku下架;
        if(spu上架状态) then (上架)
        :<spu>更新供应商状态为<部分上架>;
        :同步商家关联此商品sku为不可售;
        else
        endif
    endif

else
    :删除;
   if(操作spu) then(yes)
    :spu删除;
    :关联所有sku删除;
    else
    :sku删除;
    :当前sku删除;

    endif
:同步商家商品不可售状态;
endif
:同步商品Es索引库;
if(供应商商品状态)
:上架;
    if(操作spu) then(yes)
        :spu上架;
'        :供应商可用，非禁售;
        :关联所有sku上架;
         :供应商可用，非禁售;
        :同步商家关联此商品spu为可售;
        :同步商家关联此商品<所有>sku为可售;
        else
        :sku上架;

        :当前sku上架;
            if(spu上架状态) then (部分上架)

'            :同步商家关联此商品sku为可售;
                if(满足上架状态条件) then (上架)

                 :修改供应商状态为上架;

                 else
                 :维持部分上架状态;
                 endif
                 :供应商可用，非禁售;
                 :同步更新商家sku 可售状态;
            else
            endif
        endif
    else
    ':同步商品Es索引库;
    endif
else
:禁售;
partition 禁售逻辑 {
       :供货商品库不可见此商品;
       :供应商待审核列表显示此商品;
       :商家商品spu更新不可售状态;
       :ES同步刷新商品不可售状态;
       :C端不可见此商品;
}
:禁售成功;
partition 供应商编辑二次审核 {
'       :供货价 库存 实时同步(关联商品);
       :更新供货商品库此商品数据为最新数据;
       :之前商家导入的该商品spu可售;
       :ES同步刷新商品状态;
       :c端可见 显示最新供货价;
       :其他商家新导入改商品为最新数据;
       :之前导入的商家商品只同步供货价 库存;
}
endif;
stop
@enduml