@startuml
start
:平台禁售;
partition 禁售逻辑 {
       :供货商品库不可见此商品;
       :供应商待审核列表显示此商品;
       :商家商品只更新不可售状态;
       :C端不可见此商品;
}
:禁售成功;
partition 供应商编辑二次审核 {
       :更新供货商品库此商品数据为最新数据;
       :之前商家导入的该商品可售;
       :供货价 库存 实时同步;

}
stop
@enduml