@startuml
  alt 微信设置列表
    actor user
    control 界面类
    entity 实体类
    database 持久类
    user -> 界面类: 1.输入网址()
    界面类 -> 界面类: 2.查看微信设置界面
    界面类 -> 实体类: 3.查看微信设置列表
    实体类 -> 持久类: 4.查询支付配置信息
    持久类 -> 持久类: 5.检索支付配置数据
    实体类 -> 持久类: 4.查询第三方登陆信息
    持久类 -> 持久类: 5.检索第三方登陆表数据
    持久类 -> 实体类: 6.返回查询结果
    实体类 -> 界面类: 7.查询微信设置结果
    界面类 -> 界面类: 8.刷新显示微信设置列表
    界面类 -> user: 9.查看结果
  else 更新微信设置
    user -> 界面类: 1.输入网址()
        界面类 -> 界面类: 2.微信设置新增页面
        界面类 -> 实体类: 3.更新微信设置信息
        实体类 -> 持久类: 4.更新支付配置信息
        持久类 -> 持久类: 5.更新支付配置数据库
        实体类 -> 持久类: 4.更新第三方登陆表信息
        持久类 -> 持久类: 5.更新第三方登陆表数据库
        持久类 -> 实体类: 6.返回第三方登陆表更新结果
        实体类 -> 界面类: 7.返回微信设置更新结果
        界面类 -> 界面类: 8.刷新显示微信设置列表
        界面类 -> user: 9.查看结果
  end
@enduml