@startuml
  alt 商家端/供应商端退货地址列表
    actor user
    control 界面类
    entity 实体类
    database 持久类
    user -> 界面类: 1.输入网址()
    界面类 -> 界面类: 2.查看主页面信息
    界面类 -> 实体类: 3.查看退货地址列表
    实体类 --> 持久类: 4.查看退货地址
    持久类 --> 持久类: 5.检索数据库退货地址
    持久类 --> 实体类: 6.返回查询结果
    实体类 --> 界面类: 7.查询退货地址结果
    界面类 --> 界面类: 8.刷新显示退货地址列表
    界面类 --> user: 9.查看结果
  else 商家端/供应商端新增退货地址
    user -> 界面类: 1.输入网址()
        界面类 -> 界面类: 2.退货地址列表
        界面类 -> 实体类: 3.新增退货地址
        实体类 --> 持久类: 4.新增退货地址
        持久类 --> 持久类: 5.插入数据库
        持久类 --> 实体类: 6.返回插入结果
        实体类 --> 界面类: 7.返回退货插入结果
        界面类 --> 界面类: 8.刷新显示退货地址列表
        界面类 --> user: 9.查看结果
  end
@enduml