@startuml
start
:下载模板，按格式填写并上传，确认导入;
partition excel基础校验\n不涉及后台服务的请求
    :校验excel基本的正确性（文件大小，数据量，列名);
    :校验订单号重复&&物流号重复&&物流公司&&发货日期是否正确等;
    :将错误信息标记在对应的单元格中;

if(校验通过) then(是)
    partition 涉及order服务请求
    repeat
        :每500条数据去请求order服务,获取订单数据;
        :校验订单号是否存在&&订单状态是否可发货&&是否是部分发货;
        :校验物流单号是否重复;
        :校验订单是否申请售后;
        if(校验通过) then(是)

        else (否)
            :生成错误表格，抛出异常;
            stop;
        endif
        repeat while(全部校验完成?)
        :组装发货参数，调用order批量发货接口;
    }
else(否)
    :生成错误表格，抛出异常;
endif
stop
@enduml