@startuml
start
:立即下单/购物车点击结算;
:得到商品价格;
if(是否有参加加价购/满足条件) then (true)
  :选择加价购商品;
  :页面点击加购,加购商品传到后台;
  :后台合并加购商品到快照中;
endif;
:提交订单;
:计算商品总价和优惠金额(排除换购商品);
:得到原下单商品的金额 = 商品总价 - 优惠金额(排除换购商品);
:订单实付金额 = 原下单商品的金额 + 换购商品金额;

:下单成功;
stop
@enduml