package com.fangdeng.server.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class GoodsSyncDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.id
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.goods_no
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String goodsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.goods_supplier_type
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private Byte goodsSupplierType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.isbn
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.qty
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.edition_number
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String editionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.print_number
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String printNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.pulicate_date
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String pulicateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.print_date
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String printDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.publish_name
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String publishName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.base_price
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private BigDecimal basePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.sale_price
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private BigDecimal salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.author
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.format
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String format;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.page
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private Integer pageNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.guide
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String guide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.content
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.author_desc
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String authorDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.recommend
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.diretory
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String diretory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.wonderful_content
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String wonderfulContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.copyright_url
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String copyrightUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.bottom_url
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String bottomUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.category
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private Long category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.title
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.price
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.image_url
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.large_image_url
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String largeImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.status
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.aduit_error
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private String aduitError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.create_time
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.update_time
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync.provider_id
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    private Long providerId;

    private String detailImageUrl;
}