@startuml
start
: 开启定时(每隔1个小时)轮询任务;
: 定时任务传入订单分页参数;
: 订单推送时间配置(定制需求发货前一天，支持配置);
partition 查询订单条件{
    :子订单商品ERP编码不为空;
    :获取订单商品发货时间,
    同当前时间比较,符合推送配置时间;
    :分页条数;
    :(订单推送状态,未推送)
     或(订单推送状态,已推送&&推送次数>0次&<3次);
}
:待推送订单集合;
partition 循环订单{
    : 组装推送入参对象;
    : 调用ERP订单推送接口;
    if(接口调用是否正常) then (异常)
        :更新订单推送次数+1;
        :抛出异常;
    elseif(判断ERP返回报文) then (success=true)
        :更新订单推送状态,推送时间;
    else (success=false)
        :更新订单推送状态,推送次数+1,
        推送时间,返回报文errorDesc;
    endif;
}
stop;
@enduml