package com.fangdeng.server.mapper;

import com.fangdeng.server.dto.GoodsSyncDTO;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface GoodsSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int deleteByPrimaryKey(Long id);    /**


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int insert(GoodsSyncDTO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int insertSelective(GoodsSyncDTO record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */

    GoodsSyncDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsSyncDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int updateByPrimaryKey(GoodsSyncDTO record);

    int batchInsert(List<GoodsSyncDTO> list);
}