package com.fangdeng.server.mapper;

import com.fangdeng.server.dto.GoodsPriceSyncDTO;
import com.fangdeng.server.dto.TagDTO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


import java.util.List;

@Mapper
public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    int insert(TagDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    int insertSelective(TagDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    TagDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    int updateByPrimaryKeySelective(TagDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    int updateByPrimaryKey(TagDTO record);

    int batchInsert(@Param("list") List<String> list);

    List<TagDTO> list();
}