@startuml
 start
  :调用樊登接口返回;
  if (根据返回的樊登id查询?) then (数据库能查到该樊登用户)
    if(根据登录的手机号码查询) then(能查到手机号码)
    if(判断通过登录手机号码查询的用户樊登id是否跟返回的樊登id一致？)then(一致)
        :不做任何处理,返回登录信息;
        else(不一致)
        :现在有两种情况
        该手机号码对应在我们数据库对应的樊登id，
        跟在樊登app对应的樊登id不一致;
        :以樊登的对应关系为准,他那边应当不存在同一手机号码绑定了不同的樊登id;
        :抛出异常;
        endif
    else(查询不到手机号)
    :证明该手机号码是一个新的,
    把通过樊登id查询出来的手机号码替换成这个新的手机号码;
    endif
    else(查询不到该樊登用户)
    if(根据手机号码查询用户)then(存在用户)
    :抛出异常;
    else(不存在用户)
    :直接走注册登录流程;
    endif
  endif
  stop
@enduml