package com.fangdeng.server.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.tomcat.jni.Local;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class GoodsPriceSync {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_sync.id
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_sync.goods_no
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    private String goodsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_sync.price
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_sync.sell_price
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    private BigDecimal sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_sync.status
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_sync.create_time
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_price_sync.update_time
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    private LocalDateTime updateTime;


}