package com.fangdeng.server.entity;


import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class GoodsSyncRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync_relation.id
     *
     * @mbggenerated Wed Oct 13 17:22:27 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync_relation.goods_no
     *
     * @mbggenerated Wed Oct 13 17:22:27 CST 2021
     */
    private String goodsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync_relation.deleted
     *
     * @mbggenerated Wed Oct 13 17:22:27 CST 2021
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync_relation.create_time
     *
     * @mbggenerated Wed Oct 13 17:22:27 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync_relation.update_time
     *
     * @mbggenerated Wed Oct 13 17:22:27 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sync_relation.goods_id
     *
     * @mbggenerated Wed Oct 13 17:22:27 CST 2021
     */
    private String goodsId;


}