package com.fangdeng.server.entity;

import java.util.Date;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.id
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.tag_name
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.create_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.update_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.del_flag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    private Integer delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.id
     *
     * @return the value of t_tag.id
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public Integer getId() {
        return id;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.id
     *
     * @return the value of t_tag.id
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public String getIdByFieldName() {
        return "id";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.id
     *
     * @param id the value for t_tag.id
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.tag_name
     *
     * @return the value of t_tag.tag_name
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public String getTagName() {
        return tagName;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.tag_name
     *
     * @return the value of t_tag.tag_name
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public String getTagNameByFieldName() {
        return "tagName";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.tag_name
     *
     * @param tagName the value for t_tag.tag_name
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.create_time
     *
     * @return the value of t_tag.create_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.create_time
     *
     * @return the value of t_tag.create_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public String getCreateTimeByFieldName() {
        return "createTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.create_time
     *
     * @param createTime the value for t_tag.create_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.update_time
     *
     * @return the value of t_tag.update_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.update_time
     *
     * @return the value of t_tag.update_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public String getUpdateTimeByFieldName() {
        return "updateTime";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.update_time
     *
     * @param updateTime the value for t_tag.update_time
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.del_flag
     *
     * @return the value of t_tag.del_flag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public Integer getDelFlag() {
        return delFlag;
    }    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.del_flag
     *
     * @return the value of t_tag.del_flag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public String getDelFlagByFieldName() {
        return "delFlag";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.del_flag
     *
     * @param delFlag the value for t_tag.del_flag
     *
     * @mbggenerated Tue Oct 12 18:31:38 CST 2021
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
}