package com.fangdeng.server.mapper;

import com.fangdeng.server.dto.GoodsLabelDTO;

import java.util.List;

public interface GoodsLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_label
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    int deleteByPrimaryKey(Long goodsLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_label
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    int insert(GoodsLabelDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_label
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    int insertSelective(GoodsLabelDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_label
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    GoodsLabelDTO selectByPrimaryKey(Long goodsLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_label
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsLabelDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_label
     *
     * @mbggenerated Mon Oct 18 17:10:48 CST 2021
     */
    int updateByPrimaryKey(GoodsLabelDTO record);

    List<GoodsLabelDTO> list();
}