package com.fangdeng.server.mapper;

import com.fangdeng.server.dto.GoodsPriceSyncDTO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface  GoodsPriceSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_sync
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_sync
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    int insert(GoodsPriceSyncDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_sync
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    int insertSelective(GoodsPriceSyncDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_sync
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    GoodsPriceSyncDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_sync
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsPriceSyncDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_price_sync
     *
     * @mbggenerated Fri Sep 17 11:11:09 CST 2021
     */
    int updateByPrimaryKey(GoodsPriceSyncDTO record);

    int batchInsert(@Param("list") List<GoodsPriceSyncDTO> list);
}