package com.fangdeng.server.mapper;

import com.fangdeng.server.entity.GoodsStockSync;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface GoodsStockSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock_sync
     *
     * @mbggenerated Fri Sep 17 14:44:01 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock_sync
     *
     * @mbggenerated Fri Sep 17 14:44:01 CST 2021
     */
    int insert(GoodsStockSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock_sync
     *
     * @mbggenerated Fri Sep 17 14:44:01 CST 2021
     */
    int insertSelective(GoodsStockSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock_sync
     *
     * @mbggenerated Fri Sep 17 14:44:01 CST 2021
     */
    GoodsStockSync selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock_sync
     *
     * @mbggenerated Fri Sep 17 14:44:01 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsStockSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock_sync
     *
     * @mbggenerated Fri Sep 17 14:44:01 CST 2021
     */
    int updateByPrimaryKey(GoodsStockSync record);

    int batchInsert(@Param("list")List<GoodsStockSync> list);
}