package com.fangdeng.server.mapper;

import com.fangdeng.server.entity.GoodsSync;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface GoodsSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int deleteByPrimaryKey(Long id);    /**


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int insert(GoodsSync record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int insertSelective(GoodsSync record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */

    GoodsSync selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int updateByPrimaryKeySelective(GoodsSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sync
     *
     * @mbggenerated Wed Sep 15 10:48:18 CST 2021
     */
    int updateByPrimaryKey(GoodsSync record);

    int batchInsert(List<GoodsSync> list);

    int updateStatus(@Param("goodsNo") String goodsNo);
}