package com.wanmi.sbc.goods.common.model.root;

import lombok.Data;
import org.hibernate.annotations.Proxy;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;


@Proxy(lazy = false)
@Data
@Entity
@Table(name = "risk_verify")
public class RiskVerify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_verify.id
     *
     * @mbggenerated Wed Sep 29 14:54:57 CST 2021
     */
    @Id
    @Column(name = "id")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column risk_verify.goods_no
     *
     * @mbggenerated Wed Sep 29 14:54:57 CST 2021
     */
    @Column(name = "goods_no")
    private String goodsNo;


    @Column(name = "image_url")
    private String imageUrl;


    @Column(name = "verify_type")
    private Byte verifyType;


    @Column(name = "status")
    private Integer status;

    @Column(name = "deleted")
    private Byte deleted;

    @Column(name = "create_time")
    private Date createTime;

    @Column(name = "update_time")
    private Date updateTime;

    @Column(name = "request_id")
    private String requestId;

    @Column(name = "error_msg")
    private String errorMsg;

    @Column(name = "audit_time")
    private Date auditTime;

}