@startuml
start
:添加周期购活动;
partition 创建周期购活动 {
    if(关联活动商品（spu） || 活动名称 || 配送方案 || 配送周期 || 发货日期 || 周期运费 || 设置购买规格) then(N)
     :添加活动存在异常;
     stop
    else(Y)
      :根据关联商品ID查询商品信息，复制商品的基础信:周期购商品不需要审核、不能加入购物车、零售类型，组装商品的sku规格信息，创建商品信息入库
      组装周期购活动信息数据入库
      组装周期购赠品相关信息入库;
stop
@enduml
