package com.fandeng.server.repository;

import com.fandeng.server.entity.GoodsSpecialPriceSync;

public interface GoodsSpecialPriceSyncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_special_price_sync
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_special_price_sync
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    int insert(GoodsSpecialPriceSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_special_price_sync
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    int insertSelective(GoodsSpecialPriceSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_special_price_sync
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    GoodsSpecialPriceSync selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_special_price_sync
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    int updateByPrimaryKeySelective(GoodsSpecialPriceSync record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_special_price_sync
     *
     * @mbggenerated Mon Feb 07 13:37:12 CST 2022
     */
    int updateByPrimaryKey(GoodsSpecialPriceSync record);
}