@startuml
start
:用户点击确认导入;
:JWT获取用户身份信息
（用户id、店铺id）;
:拼接云服务resourceKey参数;
:请求云服务，下载表格;
if(表格是否存在？& 数据量是否在限制范围内) then (否)
    :抛出异常;
    stop
else (是)
    if(数据合法性校验 && SKU重复性校验 && SKU存在性校验) then (通过)
           :封装调价详情集合;
           ->**事务开始** ;
           :保存调价记录入库;
           :根据SKU ID批量查询商品信息;
           :调价详情商品信息补充;
           :调价详情入库;
           ->**事务结束**;
           :删除云服务原文件;
       else (不通过)
           :表格填充错误信息;
           :删除云服务原文件;
           :上传错误文件到云服务;
           :抛出异常：导入数据有误;
endif
:程序结束;
stop
@enduml